:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= Private Cloud Adoption

:numbered:

== Overivew
In this lab, students will be given a pre-installed OpenStack environment. They will play the role of a cloud operator and configure the environment for use by three different tenants. 

The first tenant will be configured via the Horizon UI and steps will be provided so that any students that do not have any OpenStack experience will be introduced to this workflow in a gentle manner. 

The second tenant will be added via the OpenStack CLI. Again, steps will be provided for those new to OpenStack but it is highly encouraged that users use our docs or --help from the command to work through this challenge.

The last tenant will be added via Ansible playbook(s). This lab will not provide answers and is more about Ansible and using OpenStack API.

== Lab Goals
* Provision OpenStack environment
* Configure tenant 1 via Horizon UI and setup an external network
* Configure tenant 2 via OpenStack CLI
* Configure tenant 3 via Ansible playbooks
* Stretch Lab: Ansible playbooks to teardown OpenStack environment
