:course_name: Red Hat OpenShift Container Platform 3 Implementation
:labname: Configure Authentication

:opencf: link:https://labs.opentlc.com/[OPENTLC lab portal]
:account_management: link:https://www.opentlc.com/account/[OPENTLC Account Management page]
:ocp_docs: link:https://docs.openshift.com/container-platform/3.7/welcome/index.html[OpenShift Container Platform]
:catalog_name: OPENTLC OpenShift Labs
:catalog_item_name: OpenShift Implementation HA Lab

:diagram:benefits:scrollbar:
:data-uri:
:imagesdir: images
:toc2:

== {labname}

=== Lab Goals

In this lab, you deploy and configure OpenShift 3 to use IPA for Authentication
 and synchronize (clone) existing groups from IPA.

* Set Up Lab Environment
* Configure Authentication Against IPA (LDAP) Server
** Distribute Identity Management (IdM) Certificate Authority
** Set Up IPA as Authentication Provider
** Synchronize Groups From IPA to OpenShift Cluster

=== Lab Activities

After this lab you will be able to:

* Configure Group Synchronization with an LDAP Based authentication provider.
* Deploy and Configure LDAP Authentication and Group Sync.
* Troubleshoot and verify health of OpenShift LDAP Authentication and Group Sync.


=== Important Notes

[IMPORTANT]

Read these notes. They help you successfully navigate the lab.

* You run many commands in this lab remotely from the `bastion` or `master1`
 host. Make sure you run the commands from the right host.

* This lab is long and extremely important. All future labs depend on the
 success of this section.

* Depending on your workstation's screen size, resolution, and browser, some
 commands may lose their intended formatting, appearing with extra line breaks.
  Even though this lab endeavors to avoid this pitfall, the formatting still
   "breaks" a command sometimes. Pay attention to the command you paste in and
    correct the formatting if necessary.

:numbered:

== Lab: {labname}

=== Set Up Lab Environment

If you have not done so yet, provision the environment required to complete the
 labs in the _{course_name}_ training.

. Navigate to the {opencf}.

. Log in to the portal using your OPENTLC credentials and select the
 *{catalog_item_name}* to provision your environment.

[TIP]
If you need additional information, use the lab instructions in earlier modules
 of this course.


.Provisioned Environment Hosts

These are the hosts that have been deployed in your lab environment:

* Bastion (administration) server: `bastion.$GUID.example.opentlc.com`, `bastion.$GUID.internal`
* NFS server: `support1.$GUID.example.opentlc.com`, `support1.$GUID.internal`
* Load balancer: `loadbalancer.$GUID.example.opentlc.com`, `loadbalancer1.$GUID.internal`
* 3 OpenShift master nodes: `master{1,2,3}.$GUID.example.opentlc.com`, `master{1,2,3}.$GUID.internal`
* 2 OpenShift infrastructure nodes: `infranode{1,2}.$GUID.example.opentlc.com`, `infranode{1,2}.$GUID.internal`
* 2 OpenShift worker node: `node{1,2}.$GUID.example.opentlc.com`, `node{1,2}.$GUID.internal`
* IPA Server: `ipa.shared.example.opentlc.com` (shared resource for all students)

==== Preliminary Important Notes

. *GUID*: Each lab environment is assigned a global unique identifier (GUID)
 with four characters, which you receive by email when provisioning your lab
  environment. *From this point on, replace _GUID_ with your lab's four-character GUID.*

. *Remote Access*: The bastion host is the only host that you should access with
 SSH outside the lab environment. External SSH for all other hosts is blocked.
  From the bastion host, you can access the other hosts internally through SSH.
   As described earlier, you must access the system (not as `root`) with your
    private SSH key and OPENTLC login.
. *Performance*: The lab environment is cloud based and cost-efficient, so you
 can access it over the WAN from anywhere. However, do not expect its
  performance to match a bare-metal environment.

. *Bastion host* is *not* an OpenShift cluster member or part of the OpenShift
 environment. The bastion host mimics your client's infrastructure or your
  laptop or desktop that is connected to the client's local area network (LAN).

[TIP]
It is recommended to use a terminal multiplexing tool, such as
 *tmux* or *screen*, which keeps your place in the session if you are
  disconnected from your environment. You can install their packages after
   setting up the `rhel` repositories `yum install tmux`.
If you use tmux, type *Ctrl+B* (to enter "scroll mode") + page up or down to
 scroll, and use the *Esc* key to exit scroll mode.
You can detach from tmux : `Ctrl+B  D` or simply close you terminal. To attach
 again an existing tmux session, run the command `tmux attach` once you're
  connected to the bastion host.

=== Configure Authentication Against IPA (LDAP) Server

In this section, you configure the OpenShift master API servers that you
   installed in a previous lab to authenticate against an existing IPA (LDAP)
    server and synchronize or create OpenShift group objects to match the groups
     that are configured in IPA.

* Distribute Identity Management (IdM) Certificate Authority
* Set Up IPA as Authentication Provider
* Synchronize Groups From IPA to OpenShift Cluster


==== Distribute Identity Management (IdM) Certificate Authority


The IPA server sets up its own Certificate Authority (CA) and does not use the
same CA as your OpenShift installation. In order for OpenShift to make secured
 LDAP requests to the IPA server, your master servers need the CA certificate.

. On the `bastion` host, download the `ca.crt` file:
+
[source,bash]
----
wget http://ipa.shared.example.opentlc.com/ipa/config/ca.crt -O /root/ipa-ca.crt
----

. Place it as `ipa-ca.crt` in `/etc/origin/master` on each of the masters,
 being careful not to overwrite the `ca.crt` files on the masters:
+
[source,bash]
----
ansible masters -m copy -a"src=/root/ipa-ca.crt dest=/etc/origin/master"
----

==== Set Up IPA as Authentication Provider



. Configure LDAP authentication using the Ansible installer. Use the following information to set up the authentication provider:
+
.Authentication values
[cols="1,2",caption="",options="header"]
|====
| Variable | Value
| `bindDN` | uid=admin,cn=users,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com
| `bindPassword` | r3dh4t1!
| `ca` | /etc/origin/master/ipa-ca.crt
| `url` |  ldaps://ipa.shared.example.opentlc.com:636/cn=users,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com?uid?sub?(memberOf=cn=ocp-users,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com)
|====

. Configure LDAP authentication using the Ansible installer:
.. Make sure that your Ansible inventory file contains the following in the `[OSEv3:vars]` section:
+
[source,bash]
----
openshift_master_identity_providers=[{'name': 'ldap', 'challenge': 'true', 'login': 'true', 'kind': 'LDAPPasswordIdentityProvider','attributes': {'id': ['dn'], 'email': ['mail'], 'name': ['cn'], 'preferredUsername': ['uid']}, 'bindDN': 'uid=admin,cn=users,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com', 'bindPassword': 'r3dh4t1!', 'ca': '/etc/origin/master/ipa-ca.crt','insecure': 'false', 'url': 'ldaps://ipa.shared.example.opentlc.com:636/cn=users,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com?uid?sub?(memberOf=cn=ocp-users,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com)'}]
openshift_master_ldap_ca_file=/root/ipa-ca.crt
----

.. Comment out or remove any existing `identity_providers` section and double-check
 the rest of the host file.
+
[WARNING]
This step is critical for the lab to succeed.

.. Run the installer:
+
[source,bash]
----
ansible-playbook -f 20 -i /root/my_ocp_inventory /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
----

* Expect output similar to this:
+
[source,bash]
----
PLAY RECAP *************************************************************************************************************************************************************************************************************************************************************************************************************************************************************$
infranode1.9bf4.internal   : ok=182  changed=16   unreachable=0    failed=0
infranode2.9bf4.internal   : ok=182  changed=16   unreachable=0    failed=0
loadbalancer1.9bf4.internal : ok=73   changed=4    unreachable=0    failed=0
localhost                  : ok=14   changed=0    unreachable=0    failed=0
master1.9bf4.internal      : ok=390  changed=50   unreachable=0    failed=0
master2.9bf4.internal      : ok=390  changed=50   unreachable=0    failed=0
master3.9bf4.internal      : ok=977  changed=174  unreachable=0    failed=0
node1.9bf4.internal        : ok=182  changed=16   unreachable=0    failed=0
node2.9bf4.internal        : ok=182  changed=16   unreachable=0    failed=0
node3.9bf4.internal        : ok=182  changed=16   unreachable=0    failed=0
support1.9bf4.internal     : ok=69   changed=3    unreachable=0    failed=0


INSTALLER STATUS *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************$
Initialization             : Complete
Health Check               : Complete
etcd Install               : Complete
NFS Install                : Complete
Load balancer Install      : Complete
Master Install             : Complete
Master Additional Install  : Complete
Node Install               : Complete
Hosted Install             : Complete
Metrics Install            : Complete
Logging Install            : Complete
Prometheus Install         : Complete
Service Catalog Install    : Complete
----

. Verify the configuration of the authentication provider by attempting
 to log in to the master web console.
.. Navigate to the master web console.
.. Authenticate using `payment1` as the username and `r3dh4t1!` as the password.
.. If you are unable to authenticate successfully, try restarting the
 master service manually.

NOTE: The installer in the previous section is supposed to restart the master
 service automatically, but it may not have done so.

==== Synchronize Groups From IPA to OpenShift Cluster

In this lab you will synchronize the following groups from the IPA server to
 your OpenShift cluster:
* `group/portalapp`
* `group/paymentapp`
* `group/ocp-production`
* `group/ocp-platform`

Use the following information to synchronize the groups:

.Authentication values
[cols="1,2",caption="",options="header"]
|====
| Variable | Value
| `bindDN` | uid=admin,cn=users,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com
| `bindPassword` | r3dh4t1!
| `ca` | /etc/origin/master/ipa-ca.crt
| `url` |  ldap://ipa.shared.example.opentlc.com or ldaps://ipa.shared.example.opentlc.com:636
|baseDN for *groupsQuery*| cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com
|baseDN for *usersQuery*| cn=users,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com
|filter |  (&(!(objectClass=mepManagedEntry))(!(cn=trust admins))(!(cn=groups))(!(cn=admins))(!(cn=ipausers))(!(cn=editors))(!(cn=ocp-users))(!(cn=evmgroup*))(!(cn=ipac*)))

|====

TIP: LDAP groups are referenced like this: cn=portalapp,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com

.. On the `master1` host, create the `/etc/origin/master/groupsync.yaml` file:
+
[source,bash]
----
cat << EOF > /etc/origin/master/groupsync.yaml
kind: LDAPSyncConfig
apiVersion: v1
url: "ldap://ipa.shared.example.opentlc.com"
insecure: false
ca: "/etc/origin/master/ipa-ca.crt"
bindDN: "uid=admin,cn=users,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com"
bindPassword: "r3dh4t1!"
rfc2307:
    groupsQuery:
        baseDN: "cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com"
        scope: sub
        derefAliases: never
        filter: (&(!(objectClass=mepManagedEntry))(!(cn=trust admins))(!(cn=groups))(!(cn=admins))(!(cn=ipausers))(!(cn=editors))(!(cn=ocp-users))(!(cn=evmgroup*))(!(cn=ipac*)))
    groupUIDAttribute: dn
    groupNameAttributes: [ cn ]
    groupMembershipAttributes: [ member ]
    usersQuery:
        baseDN: "cn=users,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com"
        scope: sub
        derefAliases: never
    userUIDAttribute: dn
    userNameAttributes: [ uid ]
EOF
----

.. Map LDAP groups to specific names in OpenShift by adding this section:
+
[source,yaml]
----
cat << EOF >> /etc/origin/master/groupsync.yaml
groupUIDNameMapping:
  "cn=portalapp,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com": "portalapp"
  "cn=paymentapp,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com": "paymentapp"
  "cn=ocp-production,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com": "ocp-production"
  "cn=ocp-platform,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com": "ocp-platform"
EOF
----

.. On the `master1` host, create the `/etc/origin/master/whitelist.yaml` file:
+
[source,bash]
----
cat << EOF > /etc/origin/master/whitelist.yaml
cn=portalapp,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com
cn=paymentapp,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com
cn=ocp-platform,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com
cn=ocp-production,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com
EOF
----

===== Test Run Group Synchronization

. Verify user IDs.
+
[source,bash]
----
oc get users
----

. If there are users with `htpasswd_auth`, then delete these users as shown in this example:
+
[source,bash]
----
oc delete user andrew
----

. Test running the synchronization:
+
[source,bash]
----
oc adm groups sync --sync-config=/etc/origin/master/groupsync.yaml --whitelist=/etc/origin/master/whitelist.yaml
----

* Note the YAML output for the groups created in this sample output:
+
[source,yaml]
----
apiVersion: v1
items:
- apiVersion: v1
  kind: Group
  metadata:
    annotations:
      openshift.io/ldap.sync-time: 2018-01-16T03:27:06Z
      openshift.io/ldap.uid: cn=portalapp,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com
      openshift.io/ldap.url: ipa.shared.example.opentlc.com:389
    creationTimestamp: null
    labels:
      openshift.io/ldap.host: ipa.shared.example.opentlc.com
    name: portalapp
  users:
  - andrew
  - portal1
  - portal2
- apiVersion: v1
  kind: Group
  metadata:
    annotations:
      openshift.io/ldap.sync-time: 2018-01-16T03:27:10Z
      openshift.io/ldap.uid: cn=paymentapp,cn=groups,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com
      openshift.io/ldap.url: ipa.shared.example.opentlc.com:389
    creationTimestamp: null
    labels:
      openshift.io/ldap.host: ipa.shared.example.opentlc.com
    name: paymentapp
  users:
  - marina
  - payment1
  - payment2
... OUTPUT OMITTED ...
... OUTPUT OMITTED ...
kind: List
metadata: {}
----

===== Synchronize Groups

. Run the same `oc adm groups sync` command, but add `--confirm` to create the groups:
+
[source,bash]
----
oc adm groups sync --sync-config=/etc/origin/master/groupsync.yaml --whitelist=/etc/origin/master/whitelist.yaml --confirm
----
+
* Expect the output to be similar to this example:
+
[source,bash]
----
group/portalapp
group/paymentapp
group/ocp-production
group/ocp-platform
----
endif::[]

. Verify that the groups are created:
+
[source,bash]
----
oc get groups
----
+
* Expect the output to be similar to this:
+
[source,bash]
----
NAME             USERS
ocp-platform     david, admin1, admin2
ocp-production   karla, prod1, prod2
paymentapp       marina, payment1, payment2
portalapp        andrew, portal1, portal2
----
