:scrollbar:
:data-uri:
:imagesdir: images
:toc2:
:linkattrs:
:opencf: link:https://labs.opentlc.com/[OPENTLC lab portal^]
:course_name: Red Hat OpenShift Operations
:account_management: link:https://www.opentlc.com/account/[OPENTLC Account Management page^]
:catalog_name: OPENTLC Cloud Infrastructure
:open_shared_ocp: link:https://master.na.openshift.opentlc.com/[OPENTLC OpenShift portal]
:need_client: false
:preinstalled: true


== OpenShift Certificate Authorities Redeployment Lab

.Use Case Scenario

MitziCom has its own Public Key Infrastructure (PKI) to provide keys and certificates to secure communications. The PKI administrators keep their Root CA certificate secret, and have used it to sign an Intermediate CA certificate which is dedicated to the OpenShift project. As the OpenShift administrator, you use the `openshift-ansible` deployment and management system to configure OpenShift to use this Intermediate key and certificate to secure OpenShift’s communications. The `openshift-ansible` system uses the Intermediate certificate to generate all of the certificates necessary to run OpenShift. The `openshift-ansible` system can also be used to update certificates in a running OpenShift system.

:numbered:


==== Preliminary Important Notes

. *Performance*: The lab environment is cloudased, so you can access it over
 the WAN from anywhere. However, do not expect its performance to match a
  bare-metal environment.

. *Remote Access*: The bastion host is the only host that you can access with
 SSH outside the lab environment. External SSH for all other hosts is blocked.
  From the bastion host, you can access the other hosts internally through SSH.
   As described earlier, you must access the system (not as `root`) with your
    private SSH key and OPENTLC login.

. *GUID*: Each lab environment is assigned a global unique identifier (GUID)
 with four characters, which you receive by email when provisioning your lab
  environment. *From this point on, replace _GUID_ with your lab's four-character GUID.*

. *Bastion host* is *not* an OpenShift cluster member or part of the OpenShift
 environment. The bastion host mimics your client's infrastructure or your
  laptop or desktop that is connected to the client's local area network (LAN).
+
[TIP]
It is recommended to use a terminal multiplexing tool, such as
 *tmux* or *screen*, which keeps your place in the session if you are
  disconnected from your environment. You can install their packages after
   setting up the `rhel` repositories `yum install tmux`.
If you use tmux, type *Ctrl+B* (to enter "scroll mode") + page up or down to
 scroll, and use the *Esc* key to exit scroll mode.
You can detach from tmux : `Ctrl+B  D` or simply close you terminal. To attach
 again an existing tmux session, run the command `tmux attach` once you're
  connected to the bastion host.
+
. Provisioned Environment Hosts

These are the hosts that have been deployed in your lab environment:

* Bastion (administration) server: `bastion.GUID.example.opentlc.com`, `bastion.GUID.internal`
* NFS server: `support1.GUID.example.opentlc.com`, `support1.GUID.internal`
* Load balancer: `loadbalancer.GUID.example.opentlc.com`, `loadbalancer1.GUID.internal`
* 3 OpenShift master nodes: `master{1,2,3}.GUID.example.opentlc.com`, `master{1,2,3}.GUID.internal`
* 2 OpenShift infrastructure nodes: `infranode{1,2}.GUID.example.opentlc.com`, `infranode{1,2}.GUID.internal`
* 1 OpenShift worker node: `node1.GUID.example.opentlc.com`, `node1.GUID.internal`
* IPA Server: `ipa.shared.example.opentlc.com` (shared resource for all students)

==== Connect to Bastion Host and Explore your environment

When you connect to `bastion.GUID.example.opentlc.com` for the first time, you
will have to accept the server SSH fingerprint. Reply 'yes': it will be added
 to your `known_hosts` and not asked next time you connect.

. Connect to your administration host `bastion.GUID.example.opentlc.com`. Note that your private key location may vary.
+
[source,bash]
----
yourdesktop$ ssh -i ~/.ssh/studentkey ec2-user@bastion.GUID.example.opentlc.com
----
+
* Example of a successful connection:
+
[source,bash]
----
[gucore@work ~]$ ssh -i ~/.ssh/studentkey ec2-user@bastion.9e91.example.opentlc.com
----
+
[source,text]
----
The authenticity of host 'bastion.9e91.example.opentlc.com (31.220.66.121)' can't be established.
ECDSA key fingerprint is SHA256:fR4vFVswyvpj/Jevfin3+X0Fkehbfx4HBjw46AeIS14.
ECDSA key fingerprint is MD5:bb:25:92:ee:c9:ba:23:71:b7:c1:f7:2d:89:6d:b0:66.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'bastion.9e91.example.opentlc.com,31.220.66.121' (ECDSA) to the list of known hosts.
Creating home directory for ec2-user.
[ec2-userbastion.9e91 ~]$
----

. Run `sudo -i` to become the `root` user on the bastion host:
+
[source,bash]
----
sudo -i
----
+
. Ensure that you have a GUID environment variable set to make entering commands
easier
+
[source,bash]
----
echo ${GUID}
----
+
The output should be your GUID.
+
If the output is NOT your GUID, execute the following to set your unique identifier as the GUID environment variable:
+
[source,bash]
----
export GUID=$(hostname | cut -d. -f2)
----
+
Validate that it is set, and add it to your profile.
+
[source,bash]
----
echo ${GUID}; echo "export GUID=${GUID}" >> /root/.bashrc
----


. A sample Ansible inventory file with host in your environment has been created
 for you, have a look at `/etc/ansible/hosts`
+
[source,bash]
----
cat /etc/ansible/hosts
----
+
. Use the Ansible `--list-hosts` command line to list the masters, nodes, and
 all of the host groups:
+
.. List the "masters" host group:
+
[source,bash]
----
ansible masters --list-hosts
----
+
Expect the output to look similar to this:
+
[source,text]
----
  hosts (3):
    master1.GUID.internal
    master2.GUID.internal
    master3.GUID.internal
----
+
.. List the "nodes" host group (Remember, Masters are Nodes too):
+
[source,bash]
----
ansible nodes --list-hosts
----
+
Expect the output to look similar to this:
+
[source,bash]
----
hosts (8):
    master1.GUID.internal
    master2.GUID.internal
    master3.GUID.internal
    infranode1.GUID.internal
    infranode2.GUID.internal
    node1.GUID.internal
    node2.GUID.internal
----
+
.. List the "all" host group:
+
[source,bash]
----
ansible all --list-hosts
----
+
Expect the output to look similar to this:
+
[source,text]
----
hosts (10):
    master1.GUID.internal
    master2.GUID.internal
    master3.GUID.internal
    infranode1.GUID.internal
    infranode2.GUID.internal
    node1.GUID.internal
    node2.GUID.internal
    loadbalancer1.GUID.internal
    support1.GUID.internal
----
+
. Test the Ansible configuration by using the Ansible "ping" module to contact all
the hosts.  This also ensures that all the hosts are running.:
+
[source,bash]
----
ansible all -m ping
----
+
Expect the output to look similar to this:
+
[source,text]
----
loadbalancer1.GUID.internal | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
infranode1.GUID.internal | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
master2.GUID.internal | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
master3.GUID.internal | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
master1.GUID.internal | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
infranode2.GUID.internal | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
node1.GUID.internal | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
node2.GUID.internal | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
support1.GUID.internal | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
node3.GUID.internal | SUCCESS => {
    "changed": false,
    "failed": false,
    "ping": "pong"
}
----


== Configure OpenShift to Use Intermediate CA

=== Prepare Environment


. Log in to your OpenShift Bastion host and switch to the `root` user.
+
[source,bash]
----
sudo -i
----

ifeval::[{preinstalled} == true]
. If this environment was provisioned as  a"preinstalled" environment, you can
 take the Ansible inventory file that was created to install this environment.
+
[source,bash]
----
cp /var/preserve/hosts /etc/ansible/hosts
----

endif::[]

. Set an environment variable with your environment's GUID.
+
[source,bash]
----
export GUID=$(hostname | cut -f2 -d.); echo $GUID
----


* If this was a high availability environment, the OpenShift Master API service would be accessed through the load balancer.

. Find the proper hostname and port of the Master API from the  `openshift_master_cluster_hostname` variable in the Ansible inventory file, and put it in a shell variable for ease of use:
+
[source,bash]
----
MASTER_API_HOSTPORT=`awk -F"[= ]" '/openshift_master_cluster_public_hostname/ {print $2}' /etc/ansible/hosts`:443; echo $MASTER_API_HOSTPORT
----



. Do the same for the router on the infrastructure node--the port number is `443`:
+
[source,bash]
----
ROUTER=infranode1.${GUID}.internal:443; echo ${ROUTER}
----


We've created some simple scripts to create the necessary certificates and keys for your environment.  Use them throughout the GPTE DevOps certificate labs.

. Generate the new Intermediate CA keys and special server keys on your Bastion host (if they do not already exist.)
+
[source,bash]
----
cd /root/
git clone https://github.com/newgoliath/certs/
cd certs
./ca_create.sh
----

. If that is successful, execute the following to create server keys.
+
[source,bash]
----
./create_env_certs.sh -g ${GUID}
----

=== Examine Existing Certificates

. Examine the OpenShift Platform CA certificates on the Master server with Ansible and the OpenSSL tools:
+
[source,bash]
----
ansible masters -m shell -a 'openssl x509 -text -in /etc/origin/master/ca.crt | grep Subject:'
----
+
.Sample Output
[source,text]
----
master1.GUID.internal | SUCCESS | rc=0 >>
        Subject: CN=openshift-signer@1504795784
----
* This CA certificate is known as the _OpenShift Platform CA_ because it is used to sign most of the certificates critical to the OpenShift system.
+
[NOTE]
====
The `Subject` field of the certificate is `/CN=openshift-signer@` followed by a UNIX epoch timestamp. That is the CA certificate created by default by the `openshift-ansible` deployer with the OpenShift `oc adm ca` commands when no other configuration is found. It is considered a _self-signed_ certificate, because there is no other CA certificate that has signed it. In this lab, you replace the Platform CA's self-signed certificate with the intermediate certificate, so that a common, externally generated CA can validate it and the certificates it signs.
====

. Examine the existing server certificates by getting the issuer name via a client connecting to the OpenShift API:
+
[source,bash]
----
echo QUIT | openssl s_client -connect ${MASTER_API_HOSTPORT} 2>&1 | more
----
* The `Subject` field of the `ca.crt` certificate in the section above matches the certificates in the `Certificate chain` section below:
+
.Sample Output
[source,text]
----
Thu Sep  7 11:11:49 2017

depth=1 CN = openshift-signer@1504795784
verify error:num=19:self signed certificate in certificate chain
verify return:0
CONNECTED(00000003)
---
Certificate chain
 0 s:/CN=172.30.0.1
   i:/CN=openshift-signer@1504795784
 1 s:/CN=openshift-signer@1504795784
   i:/CN=openshift-signer@1504795784
---
Server certificate
-----BEGIN CERTIFICATE-----
<OMITTED>
-----END CERTIFICATE-----
subject=/CN=172.30.0.1
issuer=/CN=openshift-signer@1504795784
---
Acceptable client certificate CA names
/CN=openshift-signer@1504795784
Server Temp Key: ECDH, prime256v1, 256 bits
----
+
[NOTE]
There is only one acceptable client certificate. This changes when you add the new CA certificate and key in a subsequent step.

. Examine the router's certificates:
+
[source,bash]
----
echo QUIT | openssl s_client -connect ${ROUTER} 2>&1 | more
----
* The router has a different CA certificate and does not express any client CA names:
+
.Sample Output
[source,text]
----
Certificate chain
 0 s:/CN=router.default.svc
   i:/CN=openshift-service-serving-signer@1504795784
 1 s:/CN=openshift-service-serving-signer@1504795784
   i:/CN=openshift-service-serving-signer@1504795784
---
Server certificate
-----BEGIN CERTIFICATE-----
<OMITTED>
-----END CERTIFICATE-----
subject=/CN=router.default.svc
issuer=/CN=openshift-service-serving-signer@1504795784
---
No client certificate CA names sent
Server Temp Key: ECDH, prime256v1, 256 bits
----


=== Deploy New Platform CA Files

. To include the new CA certificate and key, add the following lines to the `/etc/ansible/hosts` Ansible inventory file. Make sure to add the new lines in the `[OSEv3:vars]` section:
+
[source,text]
----
openshift_master_ca_certificate={'certfile': '/root/certs/ca/intermediate/certs/intermediate.cert.pem', 'keyfile': '/root/certs/ca/intermediate/private/intermediate.key.pem'}
#
# NOTE: CA certificate will not be replaced with existing clusters.
# This option may only be specified when creating a new cluster or
# when redeploying cluster certificates with the redeploy-certificates
# playbook.
----

. Run the `redeploy-openshift-ca.yml` Ansible Playbook to apply the new Intermediate CA certificate and key to the system and regenerate the necessary dependent certificates and keys:
+
[source,bash]
----
time ansible-playbook -i /etc/ansible/hosts -f 20 /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/redeploy-openshift-ca.yml
----

* The update process takes about four minutes.

=== Verify Intermediate Platform CA Certificates in Use

When the `ansible-playbook` run is complete, you verify that the certificate and key were correctly distributed to your masters and then validate their contents.

. Check that the proper files are in place by running Ansible to view the `Subject` fields of the Platform CAs:
+
[source,text]
----
ansible masters -m shell -a 'openssl x509 -text -in /etc/origin/master/ca.crt | grep Subject:'
----
+
.Sample Output
[source,text]
----
master1.GUID.internal | SUCCESS | rc=0 >>
        Subject: C=US, ST=North Carolina, O=Red Hat, Inc., OU=GPTE DevOps, CN=Red Hat OpenTLC Classroom Intermediate CA/emailAddress=gpte-devops-automation@redhat.com
----

. Examine the new certificates of the OpenShift Master API:
+
[source,bash]
----
echo QUIT | openssl s_client -connect ${MASTER_API_HOSTPORT} 2>&1 | more
----

* Note in this sample output fragment that neither the certificate chain nor the _issuer_ of the server certificate changed:
+
.Sample Output
[source,text]
----
Certificate chain
 0 s:/CN=172.30.0.1
   i:/CN=openshift-signer@1504795784
 1 s:/CN=openshift-signer@1504795784
   i:/CN=openshift-signer@1504795784
---
---
Server certificate
-----BEGIN CERTIFICATE-----
<OMITTED>
-----END CERTIFICATE-----
subject=/CN=172.30.0.1
issuer=/CN=openshift-signer@1504795784
---
----

* Also note that the acceptable client certificates _have_ changed. The output should contain certificates similar to the following:
+
.Sample Output
[source,text]
----
Acceptable client certificate CA names
/C=US/ST=North Carolina/O=Red Hat, Inc./OU=GPTE DevOps/CN=Red Hat OpenTLC Classroom Intermediate CA/emailAddress=gpte-devops-automation@redhat.com
/CN=openshift-signer@1504795784
Server Temp Key: ECDH, prime256v1, 256 bits
----
* Indicated here are the original `openshift-signer` certificate that was created upon OpenShift installation and the `/C=US/ST=North Carolina/O=Red Hat, Inc.` key that you added.

. Examine the router certificates and note that neither the issuer nor the acceptable CAs changed for the router hosts:
+
[source,bash]
----
echo QUIT | openssl s_client -connect ${ROUTER} 2>&1 | more
----
+
.Expected Output
[source,text]
----
---
Certificate chain
 0 s:/CN=router.default.svc
   i:/CN=openshift-service-serving-signer@1504795784
 1 s:/CN=openshift-service-serving-signer@1504795784
   i:/CN=openshift-service-serving-signer@1504795784
---
Server certificate
-----BEGIN CERTIFICATE-----
<OMITTED>
-----END CERTIFICATE-----
subject=/CN=router.default.svc
issuer=/CN=openshift-service-serving-signer@1504795784
---
No client certificate CA names sent
Server Temp Key: ECDH, prime256v1, 256 bits
----

== Explore OpenShift CA Certificates

In this section, you validate the various certificates generated by the
 `openshift-ansible` installer and the OpenShift system. The primary goal of
  this section to familiarize you with the various security contexts implied by
   the certificate and key generation. In this section, you gain greater
    proficiency with Ansible and OpenSSL, and explore debugging certificates and
     TLS in the OpenShift environment.

=== Explore CA Certificates in Master Configuration

In this section, you explore which certificates and keys are created when you
 update the CA certificate with Ansible. You write a short script to examine all
  of the certificates in the master configuration directory to determine their
   `subject` and `issuer`.

. Examine all of the certificates in the master configuration directory:
+
[source,bash]
----
ansible masters -m shell -a 'for x in $(ls /etc/origin/master/*.crt); do \
echo $x; openssl x509 -subject -issuer -in ${x} -noout; echo; done' | less
----

. Examine the output:
* Expect to see that _most_, but not all, of the certificates on the Master configuration are signed by the issuer of the certificate that you installed in the previous section:
+
.Sample Output
[source,text]
----
"issuer= /C=US/ST=North Carolina/O=Red Hat, Inc./OU=GPTE DevOps/CN=Red Hat OpenTLC Classroom Intermediate CA/emailAddress=gpte-devops-automation@redhat.com"
----

* Expect to see see some certificates that are _not_ signed this way and appear as follows:
+
.Sample Output
[source,text]
----
/etc/origin/master/master.etcd-ca.crt
subject= /CN=etcd-signer@1503514452
issuer= /CN=etcd-signer@1503514452
----
* These certificates are associated with the system's `etcd` and service `-signer` components.

[NOTE]
====
* There are different security contexts of those certificates signed by the CA provided, versus the certificates that are signed by a different CA.

* The `.kube` directory was modified on your master hosts. The Ansible Playbook updated the certificates necessary for the `oc` command to function.
====

=== Explore CA Certificates in Node Configurations

The nodes of the OpenShift system must also have access to certificates. In this section, you examine the difference between these certificates and those on the master hosts.

. Examine all of the certificates in the node configuration directory:
+
[source,bash]
----
ansible nodes -m shell -a 'for x in $(ls /etc/origin/node/*.crt); do \
echo $x; openssl x509 -subject -issuer -in ${x} -noout; echo;done' | less
----
+
[NOTE]
====
* Consider why all of the certificates associated with the `node` processes are signed by the CA certificate you introduced.

* Consider where the certificates for the router hosts are located.
====


== Summary

Redeploying the OpenShift Platform CA affects communication between only the master hosts, nodes, and Docker. It allows `etcd`, `router`, and `registry` to continue unchanged.

This strategy is especially useful because:

* It enhances the separation of concerns between platform administration and the rest of the components, protecting from privilege escalation.

* It allows the administrator to plan with the various teams separately for the very minor outages for the certificate replacement to occur in an orderly fashion.
