:author: Red Hat Global Partner & Technical Enablement
:sectnums!:
:hardbreaks:
:scrollbar:
:data-uri:
:toc2:
:showdetailed:

= Private Cloud Adoption - Lab 0

== Spinning Up OpenStack
. Login to https://labs.opentlc.com/
. Select `Services -> Catalogs`
. Expand `OPENTL Cloud Infrastructure`
. Order `Red Hat Tech Exchange OSP10`
. Check your email to obtain unique hostname

== Access to Lab Environment

Your OpenStack lab environment contains the following:

* External hostnames, IP addresses, Ports:
** Workstation: workstation-$GUID.rhpds.opentlc.com / see IP address in e-mail / Port 22 (ssh)
** Controller: ctrl-$GUID.rhpds.opentlc.com / see IP address in e-mail / Ports 80,443 (http/https), 6080 (novnc)
** Horizon external URL: https://ctrl-$GUID.rhpds.opentlc.com
*** Username: admin
*** Password: <instructor will provide>

* Internal hostnames, IP addresses:
** Workstation: workstation.example.com 192.168.0.5
** Controller: ctrl.example.com 192.168.0.20
** Compute0: comp00.example.com 192.168.0.30
** Compute1: comp01.example.com 192.168.0.31
** Server: server.example.com 192.168.0.80

* External cloud network (preconfigured):
** Network Name: public
** Type: flat
** Subnet Name: sub_pub
** CIDR: 192.168.0.0/16
** Allocation Pool: 192.168.0.100 - 192.168.0.200
** DHCP Allocation disabled
** Gateway: 192.168.0.2
** DNS Name Server: 192.168.0.1

=== Access Lab Workstation

. Use SSH to access the lab workstation using your private SSH key and OPENTLC SSO credentials:
.. For macOS and Linux users, execute the following:
+
[source,text]
----
$ ssh -i /path/to/your/ssh-key your-opentlc-sso-login@workstation-$GUID.rhpds.opentlc.com
----
+
[NOTE]
Replace `$GUID` with your lab environment GUID provided in the provisioning email you received when ordering.  Replace `your-opentlc-sso-login` with your OPENTLC SSO user name.

.. For Windows users, consult link:https://www.opentlc.com/ssh.html[this page^] for documentation on using PuTTY.
+
[IMPORTANT]
To avoid problems when using SSH to access your OPENTLC lab hosts, always use the FQDN host name and not the IP or Ravello DNS entry.

. After logging in, make sure you can become `root` on the lab workstation:
+
[source,text]
----
$ sudo -i
#
----

== Pre-lab coniguration
Due to some last minute changes the following changes are needed in your enviroments before we beging the rest of the labs.

=== Configure Horizon Vhost
In order to reach your Horizon host via it's public DNS name, add it as an alias so httpd is aware of it:

. Edit `/etc/httpd/conf.d/15-horizon_vhost.conf`
. Add your controller's public hostname to this file somewhere between lines 31 and 34:
+
[source,text]
----
ServerAlias ctrl-$GUID.rhpds.opentlc.com
----
+
. Restart httpd with `systemctl restart httpd`
