:author: Red Hat Global Partner & Technical Enablement
:sectnums!:
:hardbreaks:
:scrollbar:
:data-uri:
:toc2:
:showdetailed:



== Creating OpenStack Prerequesites
Before begining the Manila installation, there are a number of prerequesites that must be present in the OpenStack cluster for a successful installation and validation of the basic functionality.  Specifically in an OpenStack cluster, there must exist a properly configured tenant/project that also has configured;

In order to properly install, configure, and utilize the OpenStack Shared File System service, Manila, it is first necessary to have a configured and correctly functioning OpenStack environment.  In the first section of this lab, configure the following OpenStack constructs meant to represent a fictional tenant called `example.com`;

* Tenant / Project named `example.com`
* A user named `example-admin`
* A user named `example-user`
* Assign the `example-admin` the `admin` role in the `example.com` tenant
* RC files for both `example-admin` and `example-user`
* A Neutron network
* A Neutron subnet
* An SSH keypair
* An OpenStack security group, with rules allowing `SSH`
* A Glance image using the RHEL7 Cloud Image
* A Neutron Router with an interface on the tenant network
* An instance running RHEL7


:numbered:

. Create an OpenStack tenant
+

Create a tenant in OpenStack named `example.com` that will be used during this lab.


ifdef::showdetailed[]
+

-------------------
[root@ctrl01 ~(keystone_admin)]# openstack project create --description "Test Tenant" example.com
+-------------+----------------------------------+
| Field       | Value                            |
+-------------+----------------------------------+
| description | Test Tenant                      |
| enabled     | True                             |
| id          | 4710f42cf728433bbfcdf06d1a6cc218 |
| name        | example.com                      |
+-------------+----------------------------------+
-------------------

endif::showdetailed[]

. Create an tenant admin user
+

Create an user within the `example.com` tenant named `example-admin`.  This user will become the administrator for the `example.com` tenant.
+

[IMPORTANT]
Ensure that the password used for this user is recorded for future use.


ifdef::showdetailed[]
+

-------------------
[root@ctrl01 ~(keystone_admin)]# openstack user create --project example.com --password-prompt example-admin
User Password:
Repeat User Password:
+------------+----------------------------------+
| Field      | Value                            |
+------------+----------------------------------+
| email      | None                             |
| enabled    | True                             |
| id         | 634c25060a624ae79960a55f19abe90d |
| name       | example-admin                    |
| project_id | 4710f42cf728433bbfcdf06d1a6cc218 |
| username   | example-admin                    |
+------------+----------------------------------+
-------------------

endif::showdetailed[]

. Assign a user role
+

Assign the user just created, `example-admin` the `admin` role in the `example.com` project.


ifdef::showdetailed[]
+

-------------------
[root@ctrl01 ~(keystone_admin)]# openstack role add --project example.com --user example-admin admin
+-----------+----------------------------------+
| Field     | Value                            |
+-----------+----------------------------------+
| domain_id | None                             |
| id        | 958b430460864ab6ae4c2d40cdb9f78a |
| name      | admin                            |
+-----------+----------------------------------+
-------------------

endif::showdetailed[]


. Create a tenant user
+

Create a user in the `example.com` project named `example-user` that will be used for user operations during this lab.


ifdef::showdetailed[]
+

-------------------
[root@ctrl01 ~(keystone_admin)]# openstack user create --project example.com --password-prompt example-user
User Password:
Repeat User Password:
+------------+----------------------------------+
| Field      | Value                            |
+------------+----------------------------------+
| email      | None                             |
| enabled    | True                             |
| id         | 24534f245538427c84b613f277a2fbef |
| name       | example-user                     |
| project_id | 4710f42cf728433bbfcdf06d1a6cc218 |
| username   | example-user                     |
+------------+----------------------------------+
-------------------

endif::showdetailed[]


. Create environment files for users
+

Create shell environment files for the users that were just created that store necessary OpenStack authentication variables.  Name the files `rc_example-admin` and `rc_example-user`.


ifdef::showdetailed[]
+
.`rc_example-admin`
-------------------
export OS_USERNAME=example-admin
export OS_PASSWORD=r3dh4t1!
export OS_AUTH_URL=http://172.16.7.50:35357/v2.0
export PS1='[\u@\h \W(example-admin)]\$ '

export OS_TENANT_NAME=example.com
export OS_REGION_NAME=RegionOne
-------------------

.`rc_example-user`
-------------------
export OS_USERNAME=example-user
export OS_PASSWORD=r3dh4t1!
export OS_AUTH_URL=http://172.16.7.50:35357/v2.0
export PS1='[\u@\h \W(example-user)]\$ '

export OS_TENANT_NAME=example.com
export OS_REGION_NAME=RegionOne
-------------------

endif::showdetailed[]

. Create a tenant network
+

Create a network in the `example.com` project called `example-net` that will be used by instances and Manila.


ifdef::showdetailed[]
+

-------------------
[root@ctrl01 ~(keystone_example-admin)]# openstack network create --project example.com --internal --no-share example-net
+---------------------------+--------------------------------------+
| Field                     | Value                                |
+---------------------------+--------------------------------------+
| admin_state_up            | UP                                   |
| availability_zone_hints   |                                      |
| availability_zones        |                                      |
| created_at                | 2017-04-30T22:16:41Z                 |
| description               |                                      |
| headers                   |                                      |
| id                        | c6159372-ad02-4e26-b743-10672443d57f |
| ipv4_address_scope        | None                                 |
| ipv6_address_scope        | None                                 |
| mtu                       | 1450                                 |
| name                      | example-net                          |
| project_id                | 4710f42cf728433bbfcdf06d1a6cc218     |
| project_id                | 4710f42cf728433bbfcdf06d1a6cc218     |
| provider:network_type     | vxlan                                |
| provider:physical_network | None                                 |
| provider:segmentation_id  | 39                                   |
| revision_number           | 2                                    |
| router:external           | Internal                             |
| shared                    | False                                |
| status                    | ACTIVE                               |
| subnets                   |                                      |
| tags                      | []                                   |
| updated_at                | 2017-04-30T22:16:42Z                 |
+---------------------------+--------------------------------------+
-------------------

endif::showdetailed[]

. Create a subnet for the tenant network
+

Create a subnet that will be used by instances on the tenant network previously created.  Use the following table for details on the subnet;
+

.Subnet Details
[width="90%",frame="topbot"]
|==================
|Subnet Name | example-subnet
|Network Address | 10.43.21.0/24
|Gateway | 10.43.21.1
|Allocation Start | 10.43.21.10
|Allocation End | 10.43.21.254
|==================


ifdef::showdetailed[]
+

-------------------
[root@ctrl01 ~(keystone_example-admin)]# openstack subnet create \
    --project example.com \
    --subnet-range 10.43.21.0/24  \
    --dhcp --gateway 10.43.21.1 \
    --network example-net \
    --allocation-pool start=10.43.21.10,end=10.43.21.254 example-subnet
+-------------------+--------------------------------------+
| Field             | Value                                |
+-------------------+--------------------------------------+
| allocation_pools  | 10.43.21.10-10.43.21.254             |
| cidr              | 10.43.21.0/24                        |
| created_at        | 2017-04-30T22:21:42Z                 |
| description       |                                      |
| dns_nameservers   |                                      |
| enable_dhcp       | True                                 |
| gateway_ip        | 10.43.21.1                           |
| headers           |                                      |
| host_routes       |                                      |
| id                | 30a9e16d-b8c8-426c-8e3b-5779c512021f |
| ip_version        | 4                                    |
| ipv6_address_mode | None                                 |
| ipv6_ra_mode      | None                                 |
| name              | example-subnet                       |
| network_id        | c6159372-ad02-4e26-b743-10672443d57f |
| project_id        | 4710f42cf728433bbfcdf06d1a6cc218     |
| project_id        | 4710f42cf728433bbfcdf06d1a6cc218     |
| revision_number   | 2                                    |
| service_types     | []                                   |
| subnetpool_id     | None                                 |
| updated_at        | 2017-04-30T22:21:42Z                 |
+-------------------+--------------------------------------+
-------------------

endif::showdetailed[]

. Create a router
+

Create a router named `example-router` in the `example.com` project.


ifdef::showdetailed[]
+

-------------------
[root@ctrl01 nova(keystone_example-admin)]# openstack router create --project example.com example-router
+-------------------------+--------------------------------------+
| Field                   | Value                                |
+-------------------------+--------------------------------------+
| admin_state_up          | UP                                   |
| availability_zone_hints |                                      |
| availability_zones      |                                      |
| created_at              | 2017-04-30T22:51:43Z                 |
| description             |                                      |
| distributed             | False                                |
| external_gateway_info   | null                                 |
| flavor_id               | None                                 |
| ha                      | False                                |
| headers                 |                                      |
| id                      | 6980ef1b-439e-4d8f-aed4-f346bb9024f5 |
| name                    | example-router                       |
| project_id              | 4710f42cf728433bbfcdf06d1a6cc218     |
| project_id              | 4710f42cf728433bbfcdf06d1a6cc218     |
| revision_number         | 2                                    |
| routes                  |                                      |
| status                  | ACTIVE                               |
| updated_at              | 2017-04-30T22:51:43Z                 |
+-------------------------+--------------------------------------+
-------------------

endif::showdetailed[]


. Add an interface to the router
+

Add an interface to the `example-router` on the `example-subnet` that will serve as the gateway for that subnet.


ifdef::showdetailed[]
+

-------------------
[root@ctrl01 nova(keystone_example-admin)]# openstack router add subnet example-router example-subnet
-------------------

endif::showdetailed[]


. Validate the network namespace
+

Once the network, subnet, router, and interface have been configured; validate on the controller node that the network namespaces were properly created.


ifdef::showdetailed[]
+

First list the network namespaces

-------------------
[root@ctrl01 nova(keystone_example-admin)]# ip netns list
qrouter-6980ef1b-439e-4d8f-aed4-f346bb9024f5
qdhcp-c6159372-ad02-4e26-b743-10672443d57f
-------------------

The, examine the IP addresses in the network namespace for the `example-router`.

[NOTE]
In cases with multiple routers, the string following `qrouter` corresponds to the UUID of the router

-------------------
[root@ctrl01 nova(keystone_example-admin)]# ip netns exec qrouter-6980ef1b-439e-4d8f-aed4-f346bb9024f5 ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
11: qr-ad087375-4d: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN qlen 1000
    link/ether fa:16:3e:72:d8:3d brd ff:ff:ff:ff:ff:ff
    inet 10.43.21.1/24 brd 10.43.21.255 scope global qr-ad087375-4d
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe72:d83d/64 scope link
       valid_lft forever preferred_lft forever
-------------------

endif::showdetailed[]


. Create a SSH keypair
+

Create an SSH keypair, named `example-keypair` that can be used to authenticate remote login via SSH using the `cloud-user` account for instances launched.


ifdef::showdetailed[]
+

-------------------
[root@ctrl01 ~(keystone_example-admin)]# openstack keypair create --public-key ~/.ssh/id_rsa.pub example-keypair
+-------------+-------------------------------------------------+
| Field       | Value                                           |
+-------------+-------------------------------------------------+
| fingerprint | 2a:f7:e7:c5:dd:33:2e:77:e8:95:fa:e0:4e:74:02:ff |
| name        | example-keypair                                 |
| user_id     | 634c25060a624ae79960a55f19abe90d                |
+-------------+-------------------------------------------------+

-------------------

endif::showdetailed[]

. Create a security group
+

Create a security group named `example-secgroup` in the `example.com` project, that permits SSH traffic from any source into any instance running on the `example-subnet`.


ifdef::showdetailed[]
+

-------------------
[root@ctrl01 ~(keystone_example-admin)]# openstack security group create --project example.com example-secgroup
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field           | Value                                                                                                                                                                               |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| created_at      | 2017-04-30T22:26:39Z                                                                                                                                                                |
| description     | example-secgroup                                                                                                                                                                    |
| headers         |                                                                                                                                                                                     |
| id              | 8d121d0b-b7be-4e2b-9f9b-da33bb0e345d                                                                                                                                                |
| name            | example-secgroup                                                                                                                                                                    |
| project_id      | 4710f42cf728433bbfcdf06d1a6cc218                                                                                                                                                    |
| project_id      | 4710f42cf728433bbfcdf06d1a6cc218                                                                                                                                                    |
| revision_number | 1                                                                                                                                                                                   |
| rules           | created_at='2017-04-30T22:26:39Z', direction='egress', ethertype='IPv4', id='528a47f0-e592-460d-9a94-5233fce04ae6', project_id='4710f42cf728433bbfcdf06d1a6cc218',                  |
|                 | revision_number='1', updated_at='2017-04-30T22:26:39Z'                                                                                                                              |
|                 | created_at='2017-04-30T22:26:39Z', direction='egress', ethertype='IPv6', id='aece3442-cf46-46e3-8502-10673bd77e5a', project_id='4710f42cf728433bbfcdf06d1a6cc218',                  |
|                 | revision_number='1', updated_at='2017-04-30T22:26:39Z'                                                                                                                              |
| updated_at      | 2017-04-30T22:26:39Z                                                                                                                                                                |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

[root@ctrl01 ~(keystone_example-admin)]# openstack security group rule create --src-ip 0.0.0.0/0 --dst-port 22 --protocol tcp --ingress --project example.com example-secgroup
+-------------------+--------------------------------------+
| Field             | Value                                |
+-------------------+--------------------------------------+
| created_at        | 2017-04-30T22:28:17Z                 |
| description       |                                      |
| direction         | ingress                              |
| ethertype         | IPv4                                 |
| headers           |                                      |
| id                | b2e4f0a7-4372-487e-8982-7ca7cae5eebc |
| port_range_max    | 22                                   |
| port_range_min    | 22                                   |
| project_id        | 4710f42cf728433bbfcdf06d1a6cc218     |
| project_id        | 4710f42cf728433bbfcdf06d1a6cc218     |
| protocol          | tcp                                  |
| remote_group_id   | None                                 |
| remote_ip_prefix  | 0.0.0.0/0                            |
| revision_number   | 1                                    |
| security_group_id | 8d121d0b-b7be-4e2b-9f9b-da33bb0e345d |
| updated_at        | 2017-04-30T22:28:17Z                 |
+-------------------+--------------------------------------+
-------------------

endif::showdetailed[]


. Create a Glance image
+

Create a Glance image, using the RHEL7 Cloud Image, named `rhel7-guest`.  The RHEL7 Cloud image qcow2 file can be downloaded from `access.redhat.com`.

[NOTE]
If an account with appropriate permissions is not available, please check with the course instructor for an alternative download location.


ifdef::showdetailed[]

-------------------
[root@ctrl01 ~(keystone_example-admin)]# openstack image create --container-format bare --disk-format qcow2 --file rhel7-guest.qcow2 --project example.com rhel7-guest
+------------------+------------------------------------------------------+
| Field            | Value                                                |
+------------------+------------------------------------------------------+
| checksum         | 0bfff47b55a9428c83d2235da9d470de                     |
| container_format | bare                                                 |
| created_at       | 2017-04-30T22:37:16Z                                 |
| disk_format      | qcow2                                                |
| file             | /v2/images/ba3c75a6-0c41-42d5-9ebf-dbef0c909399/file |
| id               | ba3c75a6-0c41-42d5-9ebf-dbef0c909399                 |
| min_disk         | 0                                                    |
| min_ram          | 0                                                    |
| name             | rhel7-guest                                          |
| owner            | 4710f42cf728433bbfcdf06d1a6cc218                     |
| protected        | False                                                |
| schema           | /v2/schemas/image                                    |
| size             | 562851840                                            |
| status           | active                                               |
| tags             |                                                      |
| updated_at       | 2017-04-30T22:37:24Z                                 |
| virtual_size     | None                                                 |
| visibility       | private                                              |
+------------------+------------------------------------------------------+
-------------------

endif::showdetailed[]




. Create a test instance
+

Create a test instnance so that all settings just configured can be validated.


ifdef::showdetailed[]
+

-------------------
[root@ctrl01 nova(keystone_example-admin)]# openstack server create \
    --image rhel7-guest \
    --flavor m1.small \
    --security-group example-secgroup \
    --key-name example-keypair \
    --nic net-id=c6159372-ad02-4e26-b743-10672443d57f example-rhel7
+--------------------------------------+----------------------------------------------------+
| Field                                | Value                                              |
+--------------------------------------+----------------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                             |
| OS-EXT-AZ:availability_zone          |                                                    |
| OS-EXT-SRV-ATTR:host                 | None                                               |
| OS-EXT-SRV-ATTR:hypervisor_hostname  | None                                               |
| OS-EXT-SRV-ATTR:instance_name        |                                                    |
| OS-EXT-STS:power_state               | NOSTATE                                            |
| OS-EXT-STS:task_state                | scheduling                                         |
| OS-EXT-STS:vm_state                  | building                                           |
| OS-SRV-USG:launched_at               | None                                               |
| OS-SRV-USG:terminated_at             | None                                               |
| accessIPv4                           |                                                    |
| accessIPv6                           |                                                    |
| addresses                            |                                                    |
| adminPass                            | ATeh3nLiuy9k                                       |
| config_drive                         |                                                    |
| created                              | 2017-04-30T22:47:37Z                               |
| flavor                               | m1.small (2)                                       |
| hostId                               |                                                    |
| id                                   | 760b58cc-d23b-4d1b-b303-8937da083b43               |
| image                                | rhel7-guest (ba3c75a6-0c41-42d5-9ebf-dbef0c909399) |
| key_name                             | example-keypair                                    |
| name                                 | example-rhel7                                      |
| os-extended-volumes:volumes_attached | []                                                 |
| progress                             | 0                                                  |
| project_id                           | 4710f42cf728433bbfcdf06d1a6cc218                   |
| properties                           |                                                    |
| security_groups                      | [{u'name': u'example-secgroup'}]                   |
| status                               | BUILD                                              |
| updated                              | 2017-04-30T22:47:38Z                               |
| user_id                              | 634c25060a624ae79960a55f19abe90d                   |
+--------------------------------------+----------------------------------------------------+

-------------------

endif::showdetailed[]


. Log into the test instance
+

Once the instance has become active, use the `example-router` network namespace to SSH into the instance.  Use the `example-keypair` created previously to authenticate.

[NOTE]
It may take some time for the instance to become active and accept logins, due largely to the nested virtualization utilized in the lab environment.  Monitor instance state using the `openstack server list` and `openstack server show` commands


ifdef::showdetailed[]

-------------------
[root@ctrl01 nova(keystone_example-admin)]# ip netns exec qrouter-6980ef1b-439e-4d8f-aed4-f346bb9024f5 ssh -l cloud-user -i ~/.ssh/id_rsa 10.43.21.17
The authenticity of host '10.43.21.17 (10.43.21.17)' can't be established.
ECDSA key fingerprint is 51:e0:12:4a:97:e3:f4:c5:1f:b6:c7:bf:0e:78:84:37.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.43.21.17' (ECDSA) to the list of known hosts.
[cloud-user@example-rhel7 ~]$
-------------------

endif::showdetailed[]

