:scrollbar:
:data-uri:
:toc2:
:linkattrs:


== Introduction to Lab

:numbered:



== Lab 2 Instructions

. In your browser navigate to your pre-staged Ansible Tower. This is the *ansible1* host. The external URL to point your browser to is https://ansible1-$guid.rhpds.opentlc.com/

. Log in as `admin` with the password `r3dh4t1!`

. Create a new inventory named *Lab Hosts* and add *workstation.example.com* to this inventory.
+
Navigate to the *Inventories* tab in the Tower UI.
+
Click *+Add*. Fill in the name as *Lab Hosts* and for Organization click the find button and select *Default*. Click *Save* to create this inventory. 
+
Once the inventory we need to populate it. In this inventory we will be adding your workstation as a machine to run against. Select *+Add Host*. In host name fill in *workstation.example.com*. Click *Save* to add the workstation to the *Lab Hosts* inventory.

. Create a new project named *Webserver Configuration* which will point to a pre-populated project in Tower.
+
Navigate to the *Projects* tab. Click *+Add*. Fill in the name as *Webserver Configuration*. Click the search button for Organization and select *Default*. For SCM we are going to use *Manual* as the project is pre-populated locally on the Tower server. The directory that the projects are stored is `/var/lib/awx/projects`. For playbook directory select `webserver_config`
+
[TODO]
Add explanation of how projects get populated

. Create a new credential named *Lab Machines*
+
Navigate to the settings tab (the gear icon).
+
Navigate to *Credentials*
+
Fill in the name as *Lab Machines*. For type select *Machine* as this is going to be the credential that tower uses to SSH to the target host. 
+
Fill out the username as `awxservice` which is a local user on the workstation machine. Ensure the privilege escalation method is sudo. The `awxservice` service user has the ability to sudo to root to run commands that require priviledge escalation.
+
For private key, copy and paste the following private ssh key:
+
----
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA9nlWnc3DCGCID4QrAtCCPVMjnV6HqFK2yskXK8illJVcvE9j
FWq0TiLI6+jCFAFfQpYKmzTJ7ijf3xqhBttcd6pIOKBCWP4pGvCUn7IHn1y/hmFC
GgSd7DL0ONX9IJbMw6LAMIpwfMeZAeQyT6M8YCWBOuEv14uTNt6fHbEiIgmqQD5f
owFoQhuDvZGdq6qUlPy203sVm6+ZEsSXWi3WZeiVh4ck1ubzjERR0ZZPCnC57/w9
+tj9OrkXqMva5NrMSpY6s1HzfItNgnQPnkMdkPU9OPbFQkj5KiR7jsD3jnsn7Mih
S+zFEgkAXlMTVAoe1v9IrguXCFDnXcXwgfLqDwIDAQABAoIBAQDPDJNUsRtbmCv0
TOUM0jf2aDcM5fIz1ngz1cWfREjEjsx+bHoh7adV1CbQ9pDC2Xw6pWx3gVr4tGGM
PAR1jCUbaXKODyJtO+Uv+lX/6UA6AWHq8xziWmqHly5N6IVhsQyGc9vbaxCf4dSJ
IDebatc3NYpf+feErH2YpF8qRDkWOT443+0nx9OOAj4xXiGi4uQK/SN1zJdfaZBw
4mJm6i03ipauEFOVQeFMArGfaH2U98njFZZUtNH/yXjnPCjroA4NyZAswUdnwVbJ
mU4/KZtHHPDWRLnaztB8aQDRsS3sUv0gK9NM44Xkg1blNjk7Glm5n4N5A7llLf3E
JQkPtN9xAoGBAP59DoEzWdb2OUi4C92RQGETZ2nfU/0t2h6jCQdGtTOjAEGeUcwf
dzcXLcUtGJ6OQD4wYz69pmYLD0hP7xVYMuyQCW+UW5dcDHe9BL9mPtUeqFgJBEbR
VV8vl7+H6wT3Ab0ubNAHfjKCAKXNuGsbiGXX23NYUiUWZbp1KWSVg+LFAoGBAPfw
GIaeNKHoK6S8bFtaG5pYf/IgPlvFINYmjCVHUNmV/7m27/rTenTZIxjDuqCfNOf8
khSgqiXHlwVUgUvqj+2Tu9UzXBUDvu2HPHsBeSAqPkalLz/+gM5ZszPkAeRIB6AO
C6xACdwPXwqcTFvTHtnVvXatat4qF+A9OASIA1bDAoGAJLkFC83OK//R2lV8mNdp
89gp9xQb+Y/RRtR97AffA/mEgvOGmC7+M/vrReWxBMhAKvkuiRIy3czAws2OEYVt
q8dJJUnCQcAtqGWlNr1ZWcWXw0Rh0ppIeHjUq/XACzJdlOALIaXDJyStVT+vWf1a
HGAesbFQATwPJ+3aMEKHCoUCgYEA0oekO8LgzE5ZqNN6awOThrb5Rb7NVJ2J6W3n
+MuawnfVInxNQD4MsGWkoKWqtjMZ+JcF79ARSm01NohwFeeB+WlFyJ6I5Ss+F3GL
EKPKl15nbRNckMlp1E5klX5ZgN8M4oKqtMPX222N9XOMfzhA7RXKgJh2s1ko1vcE
twxLUYMCgYALM2eGOObX4OouXeK0o6+r3XGjWi1jZr27R5/0axxibD6QJnYW1dBw
eTNrO0pI2ridTkbL0eIOOVO8GSPMvyZLko6MdGxOoc1MAqR2F8Sltz5vAj0zBiNM
SkfvR3ErKaYjXKsFvyS2tFSmpAr8fCcGhXbycHwMD6WamkuKDbPwQw==
-----END RSA PRIVATE KEY-----
---- 

. Create a new Job Template named *Lab Webserver Configuration*
+
Navigate to the Templates tab.
+
Click *+Add* and select `Job Template`.
+
Fill in *Lab Webserver Configuration* for the name. The Job Type should be `Run`.
+
For Inventory, select the search icon and select the inventory we previously created, `Lab Hosts`
+
For the Project, select the search icon and select the Project we created, `Webserver Configuration`. For the Playbook you will want to select `playbook2.yml`.
+
For the Machine Credential we will select the `Lab Machines` credential. 
+
Because the playbook itself contains the configuration to escalate to root for it's tasks, we do not need to select `Enable Privilege Escalation`. 
+
Under `Extra Variables` we want to select `Prompt on launch`. This will allow extra variables to be passed to the playbook at instantiation time. 
+
Finally, select *Save* to create this Job Template.

. Run the *Lab Webserver Configuration* Job Template
+
Navigate to `Templates`.
+
Locate the `Lab Webserver Configuration` Job Template and click the run button (this is the rocketship button).
+
Do not input any extra variables when prompted. 
+
Observe that when the Job Template was run it is a new Job instance that is actually ran. You should see the ansible playbook log on the right side on the Job window.

. Run the Job Template again only this time passing in extra variables.
+
When prompted for extra variables, input the following YAML into the text box.
+
----
---
body_content: "Hello from the extra vars!"
----
