:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= Private Cloud Adoption - Lab 2

:numbered:

== Lab 2 Overivew
Using the same environment from lab 0, create a second tenant via OpenStack CLI. 

=== References
The following resources will be helpful in the labs that follow:

* https://docs.openstack.org/python-openstackclient/latest/

=== Access Lab Workstation

. Use SSH to access the lab workstation using your private SSH key and OPENTLC SSO credentials:
.. For macOS and Linux users, execute the following:
+
[source,text]
----
$ ssh -i /path/to/your/ssh-key your-opentlc-sso-login@workstation-$GUID.rhpds.opentlc.com
----
+
[NOTE]
Replace `$GUID` with your lab environment GUID provided in the provisioning email you received when ordering.  Replace `your-opentlc-sso-login` with your OPENTLC SSO user name.

.. For Windows users, consult link:https://www.opentlc.com/ssh.html[this page^] for documentation on using PuTTY.
+
[IMPORTANT]
To avoid problems when using SSH to access your OPENTLC lab hosts, always use the FQDN host name and not the IP or Ravello DNS entry.

. After logging in, make sure you can become `root` on the lab workstation:
+
[source,text]
----
$ sudo -i
#
----

== Lab Goals
. Configure tenant 2 via OpenStack CLI
. Upload the latest RHEL guest image into the Image service that ony this tenant can view
. Add custom security group called “TATE_CLI”
. Enable Ingress ports for icmp and SSH
. Create a network called “TATE_CLI”
. Create a subnet called “TATE_CLI”
. Create a router called “TATE_CLI” that connects your network to the public network (which has already been created)
. Boot a test server
. Assign a Floating IP to this server
. Verify you can ping and SSH to this server from outside the OpenStack environment
. Create a volume and attach it to this server
. Ensure this volume is visible in the server

== Detailed Steps

. Login to the controller node and source the `keystonerc_admin` file:
+
[source,text]
----
workstation# ssh ctrl.example.com
ctrl# source keystonerc_admin
----

. Create an OpenStack tenant
+

Create a tenant in OpenStack named `TATE_CLI` that will be used during this lab.


ifdef::showdetailed[]
+

-------------------
[root@ctrl ~(keystone_admin)]# openstack project create --description "CLI Tenant" TATE_CLI
+-------------+----------------------------------+
| Field       | Value                            |
+-------------+----------------------------------+
| description | CLI Tenant                       |
| enabled     | True                             |
| id          | 481e00e7b9564a28ae141fec82af99b8 |
| name        | TATE_CLI                         |
+-------------+----------------------------------+
-------------------

endif::showdetailed[]

. Create an tenant admin user
+

Create an user within the `TATE_CLI` tenant named `tate-cli-admin`.  This user will become the administrator for the `TATE_CLI` tenant.
+

[IMPORTANT]
Ensure that the password used for this user is recorded for future use.


ifdef::showdetailed[]
+

-------------------
[root@ctrl ~(keystone_admin)]# openstack user create --project TATE_CLI --password-prompt tate-cli-admin
User Password:
Repeat User Password:
+------------+----------------------------------+
| Field      | Value                            |
+------------+----------------------------------+
| email      | None                             |
| enabled    | True                             |
| id         | eefa496b677e45d1a784ed5ae72b675f |
| name       | tate-cli-admin                   |
| project_id | 481e00e7b9564a28ae141fec82af99b8 |
| username   | tate-cli-admin                   |
+------------+----------------------------------+
-------------------

endif::showdetailed[]

. Assign a user role
+

Assign the user just created, `tate-cli-admin` the `admin` role in the `TATE_CLI` project.


ifdef::showdetailed[]
+

-------------------
[root@ctrl ~(keystone_admin)]# openstack role add --project TATE_CLI --user tate-cli-admin admin
+-----------+----------------------------------+
| Field     | Value                            |
+-----------+----------------------------------+
| domain_id | None                             |
| id        | 2616b245a2444661bcc5380a95c5e989 |
| name      | admin                            |
+-----------+----------------------------------+
-------------------

endif::showdetailed[]


. Create a tenant user
+

Create a user in the `TATE_CLI` project named `tate-cli-user` that will be used for user operations during this lab.


ifdef::showdetailed[]
+

-------------------
[root@ctrl ~(keystone_admin)]# openstack user create --project TATE_CLI --password-prompt tate-cli-user
User Password:
Repeat User Password:
+------------+----------------------------------+
| Field      | Value                            |
+------------+----------------------------------+
| email      | None                             |
| enabled    | True                             |
| id         | 0a96e7e222ab46f98a3a03d96db79c72 |
| name       | tate-cli-user                    |
| project_id | 481e00e7b9564a28ae141fec82af99b8 |
| username   | tate-cli-user                    |
+------------+----------------------------------+
-------------------

endif::showdetailed[]


. Create environment files for users
+

Create shell environment files for the users that were just created that store necessary OpenStack authentication variables.  Name the files `rc_tate-cli-admin` and `rc_tate-cli-user`.


ifdef::showdetailed[]
+
.`rc_tate-cli-admin`
-------------------
export OS_USERNAME=tate-cli-admin
export OS_PASSWORD=r3dh4t1!
export OS_AUTH_URL=http://192.168.0.20:35357/v2.0
export PS1='[\u@\h \W(tate-cli-admin)]\$ '

export OS_TENANT_NAME=TATE_CLI
export OS_REGION_NAME=RegionOne
-------------------

.`rc_tate-cli-user`
-------------------
export OS_USERNAME=tate-cli-user
export OS_PASSWORD=r3dh4t1!
export OS_AUTH_URL=http://192.168.0.20:35357/v2.0
export PS1='[\u@\h \W(tate-cli-user)]\$ '

export OS_TENANT_NAME=TATE_CLI
export OS_REGION_NAME=RegionOne
-------------------

endif::showdetailed[]

. Create a tenant network
+

Create a network in the `TATE_CLI` project called `TATE_CLI` that will be used by instances


ifdef::showdetailed[]
+

-------------------
[root@ctrl ~(keystone_admin)]# source rc_tate-cli-admin
[root@ctrl ~(tate-cli-admin)]# openstack network create --internal --no-share TATE_CLI
+---------------------------+--------------------------------------+
| Field                     | Value                                |
+---------------------------+--------------------------------------+
| admin_state_up            | UP                                   |
| availability_zone_hints   |                                      |
| availability_zones        |                                      |
| created_at                | 2017-10-11T02:12:58Z                 |
| description               |                                      |
| headers                   |                                      |
| id                        | 3e3e273d-e3d9-418a-a081-a5c5399fada1 |
| ipv4_address_scope        | None                                 |
| ipv6_address_scope        | None                                 |
| mtu                       | 1450                                 |
| name                      | TATE_CLI                             |
| project_id                | 481e00e7b9564a28ae141fec82af99b8     |
| project_id                | 481e00e7b9564a28ae141fec82af99b8     |
| provider:network_type     | vxlan                                |
| provider:physical_network | None                                 |
| provider:segmentation_id  | 67                                   |
| revision_number           | 2                                    |
| router:external           | Internal                             |
| shared                    | False                                |
| status                    | ACTIVE                               |
| subnets                   |                                      |
| tags                      | []                                   |
| updated_at                | 2017-10-11T02:12:58Z                 |
+---------------------------+--------------------------------------+
-------------------

endif::showdetailed[]

. Create a subnet for the tenant network
+

Create a subnet that will be used by instances on the tenant network previously created.  Use the following table for details on the subnet;
+

.Subnet Details
[width="90%",frame="topbot"]
|==================
|Subnet Name  | TATE_CLI
|Subnet Range | 10.10.10.0/24
|DHCP Enabled | yes
|DNS          | 8.8.8.8
|Network      | TATE_CLI
|==================


ifdef::showdetailed[]
+

-------------------
[root@ctrl ~(tate-cli-admin)]# openstack subnet create TATE_CLI \
    --subnet-range 10.10.10.0/24 \
    --network TATE_CLI
+-------------------+--------------------------------------+
| Field             | Value                                |
+-------------------+--------------------------------------+
| allocation_pools  | 10.10.10.2-10.10.10.254              |
| cidr              | 10.10.10.0/24                        |
| created_at        | 2017-10-11T02:17:26Z                 |
| description       |                                      |
| dns_nameservers   |                                      |
| enable_dhcp       | True                                 |
| gateway_ip        | 10.10.10.1                           |
| headers           |                                      |
| host_routes       |                                      |
| id                | 57490b6d-e0e1-4873-bc5d-a0cac4004208 |
| ip_version        | 4                                    |
| ipv6_address_mode | None                                 |
| ipv6_ra_mode      | None                                 |
| name              | TATE_CLI                             |
| network_id        | 3e3e273d-e3d9-418a-a081-a5c5399fada1 |
| project_id        | 481e00e7b9564a28ae141fec82af99b8     |
| project_id        | 481e00e7b9564a28ae141fec82af99b8     |
| revision_number   | 2                                    |
| service_types     | []                                   |
| subnetpool_id     | None                                 |
| updated_at        | 2017-10-11T02:17:26Z                 |
+-------------------+--------------------------------------+
-------------------

endif::showdetailed[]

. Create a router
+

Create a router named `TATE_CLI` in the `TATE_CLI` project.


ifdef::showdetailed[]
+

-------------------
[root@ctrl (tate-cli-admin)]# openstack router create TATE_CLI
+-------------------------+--------------------------------------+
| Field                   | Value                                |
+-------------------------+--------------------------------------+
| admin_state_up          | UP                                   |
| availability_zone_hints |                                      |
| availability_zones      |                                      |
| created_at              | 2017-10-11T02:19:07Z                 |
| description             |                                      |
| distributed             | False                                |
| external_gateway_info   | null                                 |
| flavor_id               | None                                 |
| ha                      | False                                |
| headers                 |                                      |
| id                      | 37fca58c-3b26-4127-b3e1-25bd8c688f7f |
| name                    | TATE_CLI                             |
| project_id              | 481e00e7b9564a28ae141fec82af99b8     |
| project_id              | 481e00e7b9564a28ae141fec82af99b8     |
| revision_number         | 3                                    |
| routes                  |                                      |
| status                  | ACTIVE                               |
| updated_at              | 2017-10-11T02:19:07Z                 |
+-------------------------+--------------------------------------+
-------------------

endif::showdetailed[]


. Add an interface to the router
+

Add an interface to the `TATE_CLI` on the `TATE_CLI` that will serve as the gateway for that subnet.


ifdef::showdetailed[]
+

-------------------
[root@ctrl (tate-cli-admin)]# openstack router add subnet TATE_CLI TATE_CLI
-------------------

endif::showdetailed[]


. Validate the network namespace
+

Once the network, subnet, router, and interface have been configured; validate on the controller node that the network namespaces were properly created.


ifdef::showdetailed[]
+

First list the network namespaces

-------------------
[root@ctrl (tate-cli-admin)]# ip netns list
-------------------

Then, examine the IP addresses in the network namespace for the `TATE_CLI`.

[NOTE]
In cases with multiple routers, the string following `qrouter` corresponds to the UUID of the router

-------------------
[root@ctrl ~(tate-cli-admin)]# ip netns exec qrouter-de85d3bc-490c-4c0a-94c5-6efa2280339b ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
15: qg-03e513d5-55: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1000
    link/ether fa:16:3e:74:ec:82 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.110/16 brd 192.168.255.255 scope global qg-03e513d5-55
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe74:ec82/64 scope link 
       valid_lft forever preferred_lft forever
16: qr-b1d05bdc-cb: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN qlen 1000
    link/ether fa:16:3e:70:41:9c brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.1/24 brd 10.10.10.255 scope global qr-b1d05bdc-cb
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe70:419c/64 scope link 
       valid_lft forever preferred_lft forever
-------------------

endif::showdetailed[]


. Create a SSH keypair
+

Create an SSH keypair, named `TATE_CLI` that can be used to authenticate remote login via SSH using the `cloud-user` account for instances launched.


ifdef::showdetailed[]
+

-------------------
[root@ctrl ~(tate-cli-admin)]# openstack keypair create --public-key ~/.ssh/id_rsa.pub TATE_CLI
+-------------+-------------------------------------------------+
| Field       | Value                                           |
+-------------+-------------------------------------------------+
| fingerprint | 17:fb:da:a0:17:51:0d:d6:6c:50:85:92:aa:8c:cc:a2 |
| name        | TATE_CLI                                        |
| user_id     | eefa496b677e45d1a784ed5ae72b675f                |
+-------------+-------------------------------------------------+
-------------------

endif::showdetailed[]

. Create a security group
+

Create a security group named `TATE_CLI` in the `TATE_CLI` project, that permits SSH traffic from any source into any instance running on the `TATE_CLI`.


ifdef::showdetailed[]
+

-------------------
[root@ctrl ~(tate-cli-admin)]# openstack security group create TATE_CLI
+-----------------+------------------------------------------------------------------------------------------------------------------------------------+
| Field           | Value                                                                                                                              |
+-----------------+------------------------------------------------------------------------------------------------------------------------------------+
| created_at      | 2017-10-11T02:31:10Z                                                                                                               |
| description     | TATE_CLI                                                                                                                           |
| headers         |                                                                                                                                    |
| id              | 8fd66cbd-597b-4cee-b83f-75a56f84e569                                                                                               |
| name            | TATE_CLI                                                                                                                           |
| project_id      | 481e00e7b9564a28ae141fec82af99b8                                                                                                   |
| project_id      | 481e00e7b9564a28ae141fec82af99b8                                                                                                   |
| revision_number | 1                                                                                                                                  |
| rules           | created_at='2017-10-11T02:31:10Z', direction='egress', ethertype='IPv4', id='e4676159-428c-4a7a-b11c-f1f1d3dd8b3d',                |
|                 | project_id='481e00e7b9564a28ae141fec82af99b8', revision_number='1', updated_at='2017-10-11T02:31:10Z'                              |
|                 | created_at='2017-10-11T02:31:10Z', direction='egress', ethertype='IPv6', id='eec6a510-a3d7-4e7e-bce2-f604aa6d24b0',                |
|                 | project_id='481e00e7b9564a28ae141fec82af99b8', revision_number='1', updated_at='2017-10-11T02:31:10Z'                              |
| updated_at      | 2017-10-11T02:31:10Z                                                                                                               |
+-----------------+------------------------------------------------------------------------------------------------------------------------------------+

[root@ctrl ~(tate-cli-admin)]# openstack security group rule create --dst-port 22 TATE_CLI
+-------------------+--------------------------------------+
| Field             | Value                                |
+-------------------+--------------------------------------+
| created_at        | 2017-10-11T02:33:12Z                 |
| description       |                                      |
| direction         | ingress                              |
| ethertype         | IPv4                                 |
| headers           |                                      |
| id                | 1f61960a-9153-46e2-976d-f119aa296804 |
| port_range_max    | 22                                   |
| port_range_min    | 22                                   |
| project_id        | 481e00e7b9564a28ae141fec82af99b8     |
| project_id        | 481e00e7b9564a28ae141fec82af99b8     |
| protocol          | tcp                                  |
| remote_group_id   | None                                 |
| remote_ip_prefix  | 0.0.0.0/0                            |
| revision_number   | 1                                    |
| security_group_id | 8fd66cbd-597b-4cee-b83f-75a56f84e569 |
| updated_at        | 2017-10-11T02:33:12Z                 |
+-------------------+--------------------------------------+
-------------------


endif::showdetailed[]


. Create a test instance
+

Create a test instnance so that all settings just configured can be validated.


ifdef::showdetailed[]
+

-------------------
[root@ctrl ~(tate-cli-admin)]# openstack server create \
   --image rhel7 --flavor m1.small --security-group TATE_CLI --key-name TATE_CLI \
   --nic net-id=3e3e273d-e3d9-418a-a081-a5c5399fada1 example-rhel7
+--------------------------------------+----------------------------------------------+
| Field                                | Value                                        |
+--------------------------------------+----------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                       |
| OS-EXT-AZ:availability_zone          |                                              |
| OS-EXT-SRV-ATTR:host                 | None                                         |
| OS-EXT-SRV-ATTR:hypervisor_hostname  | None                                         |
| OS-EXT-SRV-ATTR:instance_name        |                                              |
| OS-EXT-STS:power_state               | NOSTATE                                      |
| OS-EXT-STS:task_state                | scheduling                                   |
| OS-EXT-STS:vm_state                  | building                                     |
| OS-SRV-USG:launched_at               | None                                         |
| OS-SRV-USG:terminated_at             | None                                         |
| accessIPv4                           |                                              |
| accessIPv6                           |                                              |
| addresses                            |                                              |
| adminPass                            | CHVYmvb5GJFn                                 |
| config_drive                         |                                              |
| created                              | 2017-10-11T02:39:00Z                         |
| flavor                               | m1.small (2)                                 |
| hostId                               |                                              |
| id                                   | 8ecf6dd3-797c-472a-b1c7-6b0d297f7f70         |
| image                                | rhel7 (13d4458e-3667-46f5-a301-cc9047a2dd54) |
| key_name                             | TATE_CLI                                     |
| name                                 | example-rhel7                                |
| os-extended-volumes:volumes_attached | []                                           |
| progress                             | 0                                            |
| project_id                           | 481e00e7b9564a28ae141fec82af99b8             |
| properties                           |                                              |
| security_groups                      | [{u'name': u'TATE_CLI'}]                     |
| status                               | BUILD                                        |
| updated                              | 2017-10-11T02:39:00Z                         |
| user_id                              | eefa496b677e45d1a784ed5ae72b675f             |
+--------------------------------------+----------------------------------------------+
-------------------

endif::showdetailed[]


. Log into the test instance
+

Once the instance has become active, use the `TATE_CLI` network namespace to SSH into the instance.  Use the `TATE_CLI` created previously to authenticate.

[NOTE]
It may take some time for the instance to become active and accept logins, due largely to the nested virtualization utilized in the lab environment.  Monitor instance state using the `openstack server list` and `openstack server show` commands


ifdef::showdetailed[]

-------------------
[root@ctrl ~(tate-cli-admin)]# ip netns exec qrouter-37fca58c-3b26-4127-b3e1-25bd8c688f7f ssh -l cloud-user -i ~/.ssh/id_rsa 10.10.10.12
The authenticity of host '10.10.10.12 (10.10.10.12)' can't be established.
ECDSA key fingerprint is SHA256:ErRs3iPnmY5z8h1kOReOfq6/t1rULvtzKFKc2EKDT3Y.
ECDSA key fingerprint is MD5:a8:00:6c:a3:ad:87:19:cf:73:06:a8:75:88:53:0d:91.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.10.10.12' (ECDSA) to the list of known hosts.
[cloud-user@example-rhel7 ~]$ 
-------------------

endif::showdetailed[]

